// exportActionTypes   (DONT DELETE THIS LINE: USED FOR BATTLECRY DUCK GENERATOR)
export const SCROLL_LOCK = 'utils/SCROLL-LOCK';
export const LOGIN_FORM = "utils/LOGIN-FORM";
export const LOGIN_REGISTER_FORM = "utils/LOGIN-REGISTER-FORM";
